### ISSUE TITLE
Box not working anymore

### ISSUE THREAD

**Issue by pilz-michael** [abel-castro/kudos-box#3]
Greetings from your former working colleagues of HTB.
Hope you are doing fine.

We would have a request about the Kudos-Box you once created for the Team Code-Black.
Looks like it is not working anymore for a few weeks. Would you do us the favor to check why the box is not working anymore?
We love to use it and it would be nice to have it back again :)

Thanks

**Comment by abel-castro** [comment]
Hi Michael, sorry for the inconveniences! I made [some security improvements](https://github.com/abel-castro/kudos-box/commit/8226032cda7024b0454c8d100a1d3186ec5a2cdb) for a while and as you already noticed, also introduced a bug. But I have fixed it [here](https://github.com/abel-castro/kudos-box/commit/1e36e640005fec719b7e3eadd6f39c84d5b0c3bf) and you should be able to use your box again.

Greets to the HTB colleagues!

**Comment by pilz-michael** [comment]
Thanks for the quick fix, we are happy to have the kudos box back :)

Wish you all the best
